version: '3.8'

services:
  react:
    build: .
    container_name: magnificentfox_react
    networks:
      - magnificentfox_net
    depends_on:
      - web  # Django app

networks:
  magnificentfox_net:
    external: true