version: '3.8'

services:
  app:
    build: .
    container_name: magnificentfox_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - magnificentfox_net

networks:
  magnificentfox_net:
    external: true  # Ensure it's the same as in `MagnificentFox`
